### ISSUE TITLE
Cannot get peacock-trame to run

### ISSUE THREAD

**Issue by SirGardener** [Kitware/peacock#4]
Dear developers of peacock-trame,

I followed the installation instructions step by step and encountered an error when trying to run peacock-trame. I have built MOOSE (with WASP) and run make in the example and test directories.

However, I am encountering the following error messages:

```
(moose) myusername@LAPTOP-3NB53JCB:~/projects/peacock-work/moose/examples$ peacock-trame -I /home/myusername/projects/peacock-work/moose/examples/ex08_materials/ex08.i
USE_PARAVIEW:  False
running executable
Traceback (most recent call last):
  File "/home/myusername/miniforge/envs/moose/bin/peacock-trame", line 8, in <module>
    sys.exit(main())
  File "/home/myusername/miniforge/envs/moose/lib/python3.10/site-packages/peacock_trame/app/main.py", line 190, in main
    engine.ui()
  File "/home/myusername/miniforge/envs/moose/lib/python3.10/site-packages/peacock_trame/app/main.py", line 133, in ui
    self.file_editor.get_ui()
  File "/home/myusername/miniforge/envs/moose/lib/python3.10/site-packages/peacock_trame/app/fileEditor.py", line 793, in get_ui
    renderView = vtk.VtkRemoteView(
  File "/home/myusername/miniforge/envs/moose/lib/python3.10/site-packages/trame_vtk/widgets/vtk/common.py", line 681, in __init__
    self._helper.has_capabilities("web", "rendering")
AttributeError: 'NoneType' object has no attribute 'has_capabilities'
```

When attempting to run with a relative path:

```
(moose) myusername@LAPTOP-3NB53JCB:~/projects/peacock-work/moose/examples$ peacock-trame -I ./moose/examples/ex08_materials/ex08.i
USE_PARAVIEW:  False
running executable
WARNING
 Problem running '/home/myusername/projects/peacock-work/moose/examples/moose/examples/ex08_materials/ex08-opt -options_left 0 --json'
WARNING
 Failed to load json from '/home/myusername/projects/peacock-work/moose/examples/moose/examples/ex08_materials/ex08-opt': Problem running '/home/myusername/projects/peacock-work/moose/examples/moose/examples/ex08_materials/ex08-opt -options_left 0 --json'
Error: [Errno 2] No such file or directory: '/home/myusername/projects/peacock-work/moose/examples/moose/examples/ex08_materials/ex08-opt'
WARNING
 setInputFile exception: Input file /home/myusername/projects/peacock-work/moose/examples/moose/examples/ex08_materials/ex08.i does not exist
Traceback (most recent call last):
  File "/home/myusername/miniforge/envs/moose/bin/peacock-trame", line 8, in <module>
    sys.exit(main())
  File "/home/myusername/miniforge/envs/moose/lib/python3.10/site-packages/peacock_trame/app/main.py", line 190, in main
    engine.ui()
  File "/home/myusername/miniforge/envs/moose/lib/python3.10/site-packages/peacock_trame/app/main.py", line 133, in ui
    self.file_editor.get_ui()
  File "/home/myusername/miniforge/envs/moose/lib/python3.10/site-packages/peacock_trame/app/fileEditor.py", line 787, in get_ui
    renderWindow = self.update_render_window()
  File "/home/myusername/miniforge/envs/moose/lib/python3.10/site-packages/peacock_trame/app/fileEditor.py", line 1054, in update_render_window
    with open(tmp_input_file, "w+") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/myusername/projects/peacock-work/moose/examples/moose/examples/ex08_materials/ex08_tmp.i'
```

I would kindly appreciate your help and advice on how to get the GUI running. Is there a way to start peacock-trame without needing to specify an input file or executable?

Thank you for your time in advance.

Kind regards,
SirGardener

**Comment by SirGardener** [comment]
Thank you,

i used my previous moose environment instead of creating a new one with paraview as suggested by the installation instructions.

After setting up the new moose-peacock environment and some tweaking I could now successfully open peacock-trame in the browser:

```
(moose-peacock) myusername@LAPTOP-3NB53JCB:~/projects/peacock-work/moose/examples$ peacock-trame -I /home/myusername/projects/peacock-work/moose/examples/ex08_materials/ex08.i
USE_PARAVIEW:  True
running executable
libEGL warning: failed to open /dev/dri/renderD128: Permission denied

libEGL warning: failed to open /dev/dri/renderD128: Permission denied

(  27.970s) [paraview        ] vtkEGLRenderWindow.cxx:381    ERR| vtkEGLRenderWindow (0x56446ff8b3d0): Only EGL 1.4 and greater allows OpenGL as client API. See eglBindAPI for more information.
(  27.990s) [paraview        ]vtkOpenGLRenderWindow.c:493    ERR| vtkEGLRenderWindow (0x56446ff8b3d0): GLEW could not be initialized: Missing GL version
libEGL warning: failed to open /dev/dri/renderD128: Permission denied

libEGL warning: failed to open /dev/dri/renderD128: Permission denied

(  28.033s) [paraview        ] vtkEGLRenderWindow.cxx:381    ERR| vtkEGLRenderWindow (0x56446ff1af70): Only EGL 1.4 and greater allows OpenGL as client API. See eglBindAPI for more information.
(  28.034s) [paraview        ]vtkOpenGLRenderWindow.c:493    ERR| vtkEGLRenderWindow (0x56446ff1af70): GLEW could not be initialized: Missing GL version

Loguru caught a signal: SIGSEGV
Stack trace:
0       0x7f999d760420 /lib/x86_64-linux-gnu/libpthread.so.0(+0x14420) [0x7f999d760420]
(  28.034s) [paraview        ]                       :0     FATL| Signal: SIGSEGV
Segmentation fault
(moose-peacock) myusername@LAPTOP-3NB53JCB:~/projects/peacock-work/moose/examples$ ^C
(moose-peacock) myusername@LAPTOP-3NB53JCB:~/projects/peacock-work/moose/examples$ sudo chmod 666 /dev/dri/renderD128
[sudo] password for myusername:
(moose-peacock) myusername@LAPTOP-3NB53JCB:~/projects/peacock-work/moose/examples$ sudo usermod -aG video $USER
(moose-peacock) myusername@LAPTOP-3NB53JCB:~/projects/peacock-work/moose/examples$ glxinfo | grep "OpenGL version"

Command 'glxinfo' not found, but can be installed with:

sudo apt install mesa-utils

(moose-peacock) myusername@LAPTOP-3NB53JCB:~/projects/peacock-work/moose/examples$ sudo apt install mesa-utils
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libfwupdplugin1 libxmlb1
Use 'sudo apt autoremove' to remove them.
The following NEW packages will be installed:
  mesa-utils
0 upgraded, 1 newly installed, 0 to remove and 183 not upgraded.
Need to get 34.2 kB of archives.
After this operation, 150 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu focal/universe amd64 mesa-utils amd64 8.4.0-1build1 [34.2 kB]
Fetched 34.2 kB in 1s (47.4 kB/s)
Selecting previously unselected package mesa-utils.
(Reading database ... 58508 files and directories currently installed.)
Preparing to unpack .../mesa-utils_8.4.0-1build1_amd64.deb ...
Unpacking mesa-utils (8.4.0-1build1) ...
Setting up mesa-utils (8.4.0-1build1) ...
Processing triggers for man-db (2.9.1-1) ...
(moose-peacock) myusername@LAPTOP-3NB53JCB:~/projects/peacock-work/moose/examples$  peacock-trame -I /home/myusername/projects/peacock-work/moose/examples/ex08_materials/ex08.i

```
